global:
  scrape_interval:     15s
  evaluation_interval: 30s  

scrape_configs:
  - job_name: 'dotnet_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:8080']


  - job_name: 'prometheus'        
    static_configs:
      - targets: ['localhost:9090']